theme: jekyll-theme-cayman
title: Human Learning @ CHI 
description: a SIG to support the learning sciences in HCI 

# remove footer
is_project_page: false

# for using repository metadata locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: siglearn/siglearn.github.io
