theme: jekyll-theme-cayman
title: Learning, Education, & HCI
description: a SIG to connect HCI and learning communities (CHI '19)

# remove footer
is_project_page: false

# for using repository metadata locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: siglearn/siglearn.github.io
